import React from 'react'
import { CircleFlag } from 'react-circle-flags'

const App = () =>
<>
  <h1>Gallery</h1>
  <div className="container">
    <div><CircleFlag countryCode="ad" /><p>Andorra (<code>AD</code>)</p></div>
    <div><CircleFlag countryCode="ae" /><p>United Arab Emirates (<code>AE</code>)</p></div>
    <div><CircleFlag countryCode="af" /><p>Afghanistan (<code>AF</code>)</p></div>
    <div><CircleFlag countryCode="ag" /><p>Antigua and Barbuda (<code>AG</code>)</p></div>
    <div><CircleFlag countryCode="ai" /><p>Anguilla (<code>AI</code>)</p></div>
    <div><CircleFlag countryCode="al" /><p>Albania (<code>AL</code>)</p></div>
    <div><CircleFlag countryCode="am" /><p>Armenia (<code>AM</code>)</p></div>
    <div><CircleFlag countryCode="ao" /><p>Angola (<code>AO</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Antarctica (<code>AQ</code>)</p></div>
    <div><CircleFlag countryCode="ar" /><p>Argentina (<code>AR</code>)</p></div>
    <div><CircleFlag countryCode="as" /><p>American Samoa (<code>AS</code>)</p></div>
    <div><CircleFlag countryCode="at" /><p>Austria (<code>AT</code>)</p></div>
    <div><CircleFlag countryCode="au" /><p>Australia (<code>AU</code>)</p></div>
    <div><CircleFlag countryCode="aw" /><p>Aruba (<code>AW</code>)</p></div>
    <div><CircleFlag countryCode="ax" /><p>Åland Islands (<code>AX</code>)</p></div>
    <div><CircleFlag countryCode="az" /><p>Azerbaijan (<code>AZ</code>)</p></div>
    <div><CircleFlag countryCode="ba" /><p>Bosnia and Herzegovina (<code>BA</code>)</p></div>
    <div><CircleFlag countryCode="bb" /><p>Barbados (<code>BB</code>)</p></div>
    <div><CircleFlag countryCode="bd" /><p>Bangladesh (<code>BD</code>)</p></div>
    <div><CircleFlag countryCode="be" /><p>Belgium (<code>BE</code>)</p></div>
    <div><CircleFlag countryCode="bf" /><p>Burkina Faso (<code>BF</code>)</p></div>
    <div><CircleFlag countryCode="bg" /><p>Bulgaria (<code>BG</code>)</p></div>
    <div><CircleFlag countryCode="bh" /><p>Bahrain (<code>BH</code>)</p></div>
    <div><CircleFlag countryCode="bi" /><p>Burundi (<code>BI</code>)</p></div>
    <div><CircleFlag countryCode="bj" /><p>Benin (<code>BJ</code>)</p></div>
    <div><CircleFlag countryCode="bl" /><p>Saint Barthélemy (<code>BL</code>)</p></div>
    <div><CircleFlag countryCode="bm" /><p>Bermuda (<code>BM</code>)</p></div>
    <div><CircleFlag countryCode="bn" /><p>Brunei (<code>BN</code>)</p></div>
    <div><CircleFlag countryCode="bo" /><p>Bolivia (<code>BO</code>)</p></div>
    <div><CircleFlag countryCode="bq-bo"/><p>Bonaire (<code>BQ</code>)</p></div>
    <div><CircleFlag countryCode="bq-sa"/><p>Saba (<code>BQ</code>)</p></div>
    <div><CircleFlag countryCode="bq-se"/><p>Sint Eustatius (<code>BQ</code>)</p></div>
    <div><CircleFlag countryCode="br" /><p>Brazil (<code>BR</code>)</p></div>
    <div><CircleFlag countryCode="bs" /><p>Bahamas (<code>BS</code>)</p></div>
    <div><CircleFlag countryCode="bt" /><p>Bhutan (<code>BT</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Bouvet Island (<code>BV</code>)</p></div>
    <div><CircleFlag countryCode="bw" /><p>Botswana (<code>BW</code>)</p></div>
    <div><CircleFlag countryCode="by" /><p>Belarus (<code>BY</code>)</p></div>
    <div><CircleFlag countryCode="bz" /><p>Belize (<code>BZ</code>)</p></div>
    <div><CircleFlag countryCode="ca-bc"/><p>British Columbia</p></div>
    <div><CircleFlag countryCode="ca" /><p>Canada (<code>CA</code>)</p></div>
    <div><CircleFlag countryCode="cc" /><p>Cocos (Keeling) Islands (<code>CC</code>)</p></div>
    <div><CircleFlag countryCode="cd" /><p>Congo, Democratic Republic of the (<code>CD</code>)</p></div>
    <div><CircleFlag countryCode="cf" /><p>Central African Republic (<code>CF</code>)</p></div>
    <div><CircleFlag countryCode="cg" /><p>Congo (<code>CG</code>)</p></div>
    <div><CircleFlag countryCode="ch" /><p>Switzerland (<code>CH</code>)</p></div>
    <div><CircleFlag countryCode="ci" /><p>Ivory Coast (<code>CI</code>)</p></div>
    <div><CircleFlag countryCode="ck" /><p>Cook Islands (<code>CK</code>)</p></div>
    <div><CircleFlag countryCode="cl" /><p>Chile (<code>CL</code>)</p></div>
    <div><CircleFlag countryCode="cm" /><p>Cameroon (<code>CM</code>)</p></div>
    <div><CircleFlag countryCode="cn" /><p>China (<code>CN</code>)</p></div>
    <div><CircleFlag countryCode="co" /><p>Colombia (<code>CO</code>)</p></div>
    <div><CircleFlag countryCode="cr" /><p>Costa Rica (<code>CR</code>)</p></div>
    <div><CircleFlag countryCode="cu" /><p>Cuba (<code>CU</code>)</p></div>
    <div><CircleFlag countryCode="cv" /><p>Cabo Verde (<code>CV</code>)</p></div>
    <div><CircleFlag countryCode="cw" /><p>Curaçao (<code>CW</code>)</p></div>
    <div><CircleFlag countryCode="cx" /><p>Christmas Island (<code>CX</code>)</p></div>
    <div><CircleFlag countryCode="cy" /><p>Cyprus (<code>CY</code>)</p></div>
    <div><CircleFlag countryCode="cz" /><p>Czechia (<code>CZ</code>)</p></div>
    <div><CircleFlag countryCode="de" /><p>Germany (<code>DE</code>)</p></div>
    <div><CircleFlag countryCode="dj" /><p>Djibouti (<code>DJ</code>)</p></div>
    <div><CircleFlag countryCode="dk" /><p>Denmark (<code>DK</code>)</p></div>
    <div><CircleFlag countryCode="dm" /><p>Dominica (<code>DM</code>)</p></div>
    <div><CircleFlag countryCode="do" /><p>Dominican Republic (<code>DO</code>)</p></div>
    <div><CircleFlag countryCode="dz" /><p>Algeria (<code>DZ</code>)</p></div>
    <div><CircleFlag countryCode="easter_island" /><p>Easter Island</p></div>
    <div><CircleFlag countryCode="ec-w"/><p>Galápagos</p></div>
    <div><CircleFlag countryCode="ec" /><p>Ecuador (<code>EC</code>)</p></div>
    <div><CircleFlag countryCode="ee" /><p>Estonia (<code>EE</code>)</p></div>
    <div><CircleFlag countryCode="eg" /><p>Egypt (<code>EG</code>)</p></div>
    <div><CircleFlag countryCode="eh" /><p>Western Sahara (<code>EH</code>)</p></div>
    <div><CircleFlag countryCode="er" /><p>Eritrea (<code>ER</code>)</p></div>
    <div><CircleFlag countryCode="es-ce"/><p>Ceuta</p></div>
    <div><CircleFlag countryCode="es-cn"/><p>Canary Islands</p></div>
    <div><CircleFlag countryCode="es-ga"/><p>Galicia</p></div>
    <div><CircleFlag countryCode="es-ib"/><p>Balearic Islands</p></div>
    <div><CircleFlag countryCode="es-ml"/><p>Melilla</p></div>
    <div><CircleFlag countryCode="es-pv"/><p>Basque Country</p></div>
    <div><CircleFlag countryCode="es" /><p>Spain (<code>ES</code>)</p></div>
    <div><CircleFlag countryCode="esperanto" /><p>Esperanto</p></div>
    <div><CircleFlag countryCode="et" /><p>Ethiopia (<code>ET</code>)</p></div>
    <div><CircleFlag countryCode="european_union" /><p>European Union</p></div>
    <div><CircleFlag countryCode="fi" /><p>Finland (<code>FI</code>)</p></div>
    <div><CircleFlag countryCode="fj" /><p>Fiji (<code>FJ</code>)</p></div>
    <div><CircleFlag countryCode="fk" /><p>Falkland Islands (Malvinas) (<code>FK</code>)</p></div>
    <div><CircleFlag countryCode="fm" /><p>Micronesia (<code>FM</code>)</p></div>
    <div><CircleFlag countryCode="fo" /><p>Faroe Islands (<code>FO</code>)</p></div>
    <div><CircleFlag countryCode="fr-h"/><p>Corsica</p></div>
    <div><CircleFlag countryCode="fr" /><p>France (<code>FR</code>)</p></div>
    <div><CircleFlag countryCode="ga" /><p>Gabon (<code>GA</code>)</p></div>
    <div><CircleFlag countryCode="gb-eng"/><p>England</p></div>
    <div><CircleFlag countryCode="gb-ork"/><p>Orkney</p></div>
    <div><CircleFlag countryCode="gb-sct"/><p>Scotland</p></div>
    <div><CircleFlag countryCode="gb-wls"/><p>Wales</p></div>
    <div><CircleFlag countryCode="gb" /><p>United Kingdom (<code>GB</code>)</p></div>
    <div><CircleFlag countryCode="gd" /><p>Grenada (<code>GD</code>)</p></div>
    <div><CircleFlag countryCode="ge-ab"/><p>Georgia (<code>GE</code>)</p></div>
    <div><CircleFlag countryCode="ge" /><p>French Guiana (<code>GF</code>)</p></div>
    <div><CircleFlag countryCode="gg" /><p>Guernsey (<code>GG</code>)</p></div>
    <div><CircleFlag countryCode="gh" /><p>Ghana (<code>GH</code>)</p></div>
    <div><CircleFlag countryCode="gi" /><p>Gibraltar (<code>GI</code>)</p></div>
    <div><CircleFlag countryCode="gl" /><p>Greenland (<code>GL</code>)</p></div>
    <div><CircleFlag countryCode="gm" /><p>Gambia (<code>GM</code>)</p></div>
    <div><CircleFlag countryCode="gn" /><p>Guinea (<code>GN</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Guadeloupe (<code>GP</code>)</p></div>
    <div><CircleFlag countryCode="gq" /><p>Equatorial Guinea (<code>GQ</code>)</p></div>
    <div><CircleFlag countryCode="gr" /><p>Greece (<code>GR</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>South Georgia and the South Sandwich Islands (<code>GS</code>)</p></div>
    <div><CircleFlag countryCode="gt" /><p>Guatemala (<code>GT</code>)</p></div>
    <div><CircleFlag countryCode="gu" /><p>Guam (<code>GU</code>)</p></div>
    <div><CircleFlag countryCode="gw" /><p>Guinea-Bissau (<code>GW</code>)</p></div>
    <div><CircleFlag countryCode="gy" /><p>Guyana (<code>GY</code>)</p></div>
    <div><CircleFlag countryCode="hausa" /><p>Hausa</p></div>
    <div><CircleFlag countryCode="hk" /><p>Hong Kong (<code>HK</code>)</p></div>
    <div><CircleFlag countryCode="hmong" /><p>Hmong</p></div>
    <div><CircleFlag countryCode="xx" /><p>Heard Island and McDonald Islands (<code>HM</code>)</p></div>
    <div><CircleFlag countryCode="hn" /><p>Honduras (<code>HN</code>)</p></div>
    <div><CircleFlag countryCode="hr" /><p>Croatia (<code>HR</code>)</p></div>
    <div><CircleFlag countryCode="ht" /><p>Haiti (<code>HT</code>)</p></div>
    <div><CircleFlag countryCode="hu" /><p>Hungary (<code>HU</code>)</p></div>
    <div><CircleFlag countryCode="id" /><p>Indonesia (<code>ID</code>)</p></div>
    <div><CircleFlag countryCode="ie" /><p>Ireland (<code>IE</code>)</p></div>
    <div><CircleFlag countryCode="il" /><p>Israel (<code>IL</code>)</p></div>
    <div><CircleFlag countryCode="im" /><p>Isle of Man (<code>IM</code>)</p></div>
    <div><CircleFlag countryCode="in" /><p>India (<code>IN</code>)</p></div>
    <div><CircleFlag countryCode="io" /><p>British Indian Ocean Territory (<code>IO</code>)</p></div>
    <div><CircleFlag countryCode="iq" /><p>Iraq (<code>IQ</code>)</p></div>
    <div><CircleFlag countryCode="ir" /><p>Iran (<code>IR</code>)</p></div>
    <div><CircleFlag countryCode="is" /><p>Iceland (<code>IS</code>)</p></div>
    <div><CircleFlag countryCode="it-82"/><p>Sicily</p></div>
    <div><CircleFlag countryCode="it-88"/><p>Sardinia</p></div>
    <div><CircleFlag countryCode="it" /><p>Italy (<code>IT</code>)</p></div>
    <div><CircleFlag countryCode="je" /><p>Jersey (<code>JE</code>)</p></div>
    <div><CircleFlag countryCode="jm" /><p>Jamaica (<code>JM</code>)</p></div>
    <div><CircleFlag countryCode="jo" /><p>Jordan (<code>JO</code>)</p></div>
    <div><CircleFlag countryCode="jp" /><p>Japan (<code>JP</code>)</p></div>
    <div><CircleFlag countryCode="kannada" /><p>Kannada</p></div>
    <div><CircleFlag countryCode="ke" /><p>Kenya (<code>KE</code>)</p></div>
    <div><CircleFlag countryCode="kg" /><p>Kyrgyzstan (<code>KG</code>)</p></div>
    <div><CircleFlag countryCode="kh" /><p>Cambodia (<code>KH</code>)</p></div>
    <div><CircleFlag countryCode="ki" /><p>Kiribati (<code>KI</code>)</p></div>
    <div><CircleFlag countryCode="km" /><p>Comoros (<code>KM</code>)</p></div>
    <div><CircleFlag countryCode="kn" /><p>Saint Kitts and Nevis (<code>KN</code>)</p></div>
    <div><CircleFlag countryCode="kp" /><p>North Korea (<code>KP</code>)</p></div>
    <div><CircleFlag countryCode="kr" /><p>South Korea (<code>KR</code>)</p></div>
    <div><CircleFlag countryCode="kurdistan" /><p>Kurdistan</p></div>
    <div><CircleFlag countryCode="kw" /><p>Kuwait (<code>KW</code>)</p></div>
    <div><CircleFlag countryCode="ky" /><p>Cayman Islands (<code>KY</code>)</p></div>
    <div><CircleFlag countryCode="kz" /><p>Kazakhstan (<code>KZ</code>)</p></div>
    <div><CircleFlag countryCode="la" /><p>Laos (<code>LA</code>)</p></div>
    <div><CircleFlag countryCode="lb" /><p>Lebanon (<code>LB</code>)</p></div>
    <div><CircleFlag countryCode="lc" /><p>Saint Lucia (<code>LC</code>)</p></div>
    <div><CircleFlag countryCode="li" /><p>Liechtenstein (<code>LI</code>)</p></div>
    <div><CircleFlag countryCode="lk" /><p>Sri Lanka (<code>LK</code>)</p></div>
    <div><CircleFlag countryCode="lr" /><p>Liberia (<code>LR</code>)</p></div>
    <div><CircleFlag countryCode="ls" /><p>Lesotho (<code>LS</code>)</p></div>
    <div><CircleFlag countryCode="lt" /><p>Lithuania (<code>LT</code>)</p></div>
    <div><CircleFlag countryCode="lu" /><p>Luxembourg (<code>LU</code>)</p></div>
    <div><CircleFlag countryCode="lv" /><p>Latvia (<code>LV</code>)</p></div>
    <div><CircleFlag countryCode="ly" /><p>Libya (<code>LY</code>)</p></div>
    <div><CircleFlag countryCode="ma" /><p>Morocco (<code>MA</code>)</p></div>
    <div><CircleFlag countryCode="malayali" /><p>Malayali</p></div>
    <div><CircleFlag countryCode="maori" /><p>Maori</p></div>
    <div><CircleFlag countryCode="mc" /><p>Monaco (<code>MC</code>)</p></div>
    <div><CircleFlag countryCode="md" /><p>Moldova (<code>MD</code>)</p></div>
    <div><CircleFlag countryCode="me" /><p>Montenegro (<code>ME</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Saint-Martin (<code>MF</code>)</p></div>
    <div><CircleFlag countryCode="mg" /><p>Madagascar (<code>MG</code>)</p></div>
    <div><CircleFlag countryCode="mh" /><p>Marshall Islands (<code>MH</code>)</p></div>
    <div><CircleFlag countryCode="mk" /><p>North Macedonia (<code>MK</code>)</p></div>
    <div><CircleFlag countryCode="ml" /><p>Mali (<code>ML</code>)</p></div>
    <div><CircleFlag countryCode="mm" /><p>Myanmar (<code>MM</code>)</p></div>
    <div><CircleFlag countryCode="mn" /><p>Mongolia (<code>MN</code>)</p></div>
    <div><CircleFlag countryCode="mo" /><p>Macao (<code>MO</code>)</p></div>
    <div><CircleFlag countryCode="mp" /><p>Northern Mariana Islands (<code>MP</code>)</p></div>
    <div><CircleFlag countryCode="mq" /><p>Martinique (<code>MQ</code>)</p></div>
    <div><CircleFlag countryCode="mr" /><p>Mauritania (<code>MR</code>)</p></div>
    <div><CircleFlag countryCode="ms" /><p>Montserrat (<code>MS</code>)</p></div>
    <div><CircleFlag countryCode="mt" /><p>Malta (<code>MT</code>)</p></div>
    <div><CircleFlag countryCode="mu" /><p>Mauritius (<code>MU</code>)</p></div>
    <div><CircleFlag countryCode="mv" /><p>Maldives (<code>MV</code>)</p></div>
    <div><CircleFlag countryCode="mw" /><p>Malawi (<code>MW</code>)</p></div>
    <div><CircleFlag countryCode="mx" /><p>Mexico (<code>MX</code>)</p></div>
    <div><CircleFlag countryCode="my" /><p>Malaysia (<code>MY</code>)</p></div>
    <div><CircleFlag countryCode="mz" /><p>Mozambique (<code>MZ</code>)</p></div>
    <div><CircleFlag countryCode="na" /><p>Namibia (<code>NA</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>New Caledonia (<code>NC</code>)</p></div>
    <div><CircleFlag countryCode="nato" /><p>NATO</p></div>
    <div><CircleFlag countryCode="ne" /><p>Niger (<code>NE</code>)</p></div>
    <div><CircleFlag countryCode="nf" /><p>Norfolk Island (<code>NF</code>)</p></div>
    <div><CircleFlag countryCode="ng" /><p>Nigeria (<code>NG</code>)</p></div>
    <div><CircleFlag countryCode="ni" /><p>Nicaragua (<code>NI</code>)</p></div>
    <div><CircleFlag countryCode="nl" /><p>Netherlands (<code>NL</code>)</p></div>
    <div><CircleFlag countryCode="no" /><p>Norway (<code>NO</code>)</p></div>
    <div><CircleFlag countryCode="northern_cyprus" /><p>Northern Cyprus</p></div>
    <div><CircleFlag countryCode="np" /><p>Nepal (<code>NP</code>)</p></div>
    <div><CircleFlag countryCode="nr" /><p>Nauru (<code>NR</code>)</p></div>
    <div><CircleFlag countryCode="nu" /><p>Niue (<code>NU</code>)</p></div>
    <div><CircleFlag countryCode="nz" /><p>New Zealand (<code>NZ</code>)</p></div>
    <div><CircleFlag countryCode="om" /><p>Oman (<code>OM</code>)</p></div>
    <div><CircleFlag countryCode="pa" /><p>Panama (<code>PA</code>)</p></div>
    <div><CircleFlag countryCode="pe" /><p>Peru (<code>PE</code>)</p></div>
    <div><CircleFlag countryCode="pf" /><p>French Polynesia (<code>PF</code>)</p></div>
    <div><CircleFlag countryCode="pg" /><p>Papua New Guinea (<code>PG</code>)</p></div>
    <div><CircleFlag countryCode="ph" /><p>Philippines (<code>PH</code>)</p></div>
    <div><CircleFlag countryCode="pk" /><p>Pakistan (<code>PK</code>)</p></div>
    <div><CircleFlag countryCode="pl" /><p>Poland (<code>PL</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Saint Pierre and Miquelon (<code>PM</code>)</p></div>
    <div><CircleFlag countryCode="pn" /><p>Pitcairn Islands (<code>PN</code>)</p></div>
    <div><CircleFlag countryCode="pr" /><p>Puerto Rico (<code>PR</code>)</p></div>
    <div><CircleFlag countryCode="ps" /><p>Palestine (<code>PS</code>)</p></div>
    <div><CircleFlag countryCode="pt-20"/><p>Azores</p></div>
    <div><CircleFlag countryCode="pt-30"/><p>Madeira</p></div>
    <div><CircleFlag countryCode="pt" /><p>Portugal (<code>PT</code>)</p></div>
    <div><CircleFlag countryCode="pw" /><p>Palau (<code>PW</code>)</p></div>
    <div><CircleFlag countryCode="py" /><p>Paraguay (<code>PY</code>)</p></div>
    <div><CircleFlag countryCode="qa" /><p>Qatar (<code>QA</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Réunion (<code>RE</code>)</p></div>
    <div><CircleFlag countryCode="ro" /><p>Romania (<code>RO</code>)</p></div>
    <div><CircleFlag countryCode="rs" /><p>Serbia (<code>RS</code>)</p></div>
    <div><CircleFlag countryCode="ru" /><p>Russia (<code>RU</code>)</p></div>
    <div><CircleFlag countryCode="rw" /><p>Rwanda (<code>RW</code>)</p></div>
    <div><CircleFlag countryCode="sa" /><p>Saudi Arabia (<code>SA</code>)</p></div>
    <div><CircleFlag countryCode="sb" /><p>Solomon Islands (<code>SB</code>)</p></div>
    <div><CircleFlag countryCode="sc" /><p>Seychelles (<code>SC</code>)</p></div>
    <div><CircleFlag countryCode="sd" /><p>Sudan (<code>SD</code>)</p></div>
    <div><CircleFlag countryCode="se" /><p>Sweden (<code>SE</code>)</p></div>
    <div><CircleFlag countryCode="sg" /><p>Singapore (<code>SG</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Saint Helena (<code>SH-HL</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Ascension Island (<code>SH-AC</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Tristan da Cunha (<code>SH-TA</code>)</p></div>
    <div><CircleFlag countryCode="si" /><p>Slovenia (<code>SI</code>)</p></div>
    <div><CircleFlag countryCode="sindh" /><p>Svalbard and Jan Mayen (<code>SJ</code>)</p></div>
    <div><CircleFlag countryCode="sk" /><p>Slovakia (<code>SK</code>)</p></div>
    <div><CircleFlag countryCode="sl" /><p>Sierra Leone (<code>SL</code>)</p></div>
    <div><CircleFlag countryCode="sm" /><p>San Marino (<code>SM</code>)</p></div>
    <div><CircleFlag countryCode="sn" /><p>Senegal (<code>SN</code>)</p></div>
    <div><CircleFlag countryCode="so" /><p>Somalia (<code>SO</code>)</p></div>
    <div><CircleFlag countryCode="somaliland" /><p>Somaliland</p></div>
    <div><CircleFlag countryCode="south_ossetia" /><p>South Ossetia</p></div>
    <div><CircleFlag countryCode="sr" /><p>Suriname (<code>SR</code>)</p></div>
    <div><CircleFlag countryCode="ss" /><p>South Sudan (<code>SS</code>)</p></div>
    <div><CircleFlag countryCode="st" /><p>São Tomé and Príncipe (<code>ST</code>)</p></div>
    <div><CircleFlag countryCode="sv" /><p>El Salvador (<code>SV</code>)</p></div>
    <div><CircleFlag countryCode="sx" /><p>Sint Maarten (<code>SX</code>)</p></div>
    <div><CircleFlag countryCode="sy" /><p>Syria (<code>SY</code>)</p></div>
    <div><CircleFlag countryCode="sz" /><p>Eswatini (<code>SZ</code>)</p></div>
    <div><CircleFlag countryCode="tc" /><p>Turks and Caicos Islands (<code>TC</code>)</p></div>
    <div><CircleFlag countryCode="td" /><p>Chad (<code>TD</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>French Southern Territories (<code>TF</code>)</p></div>
    <div><CircleFlag countryCode="tg" /><p>Togo (<code>TG</code>)</p></div>
    <div><CircleFlag countryCode="th" /><p>Thailand (<code>TH</code>)</p></div>
    <div><CircleFlag countryCode="tibet" /><p>Tibet</p></div>
    <div><CircleFlag countryCode="tj" /><p>Tajikistan (<code>TJ</code>)</p></div>
    <div><CircleFlag countryCode="tk" /><p>Tokelau (<code>TK</code>)</p></div>
    <div><CircleFlag countryCode="tl" /><p>Timor-Leste (<code>TL</code>)</p></div>
    <div><CircleFlag countryCode="tm" /><p>Turkmenistan (<code>TM</code>)</p></div>
    <div><CircleFlag countryCode="tn" /><p>Tunisia (<code>TN</code>)</p></div>
    <div><CircleFlag countryCode="to" /><p>Tonga (<code>TO</code>)</p></div>
    <div><CircleFlag countryCode="tr" /><p>Turkey (<code>TR</code>)</p></div>
    <div><CircleFlag countryCode="transnistria" /><p>Transnistria</p></div>
    <div><CircleFlag countryCode="tt" /><p>Trinidad and Tobago (<code>TT</code>)</p></div>
    <div><CircleFlag countryCode="tv" /><p>Tuvalu (<code>TV</code>)</p></div>
    <div><CircleFlag countryCode="tw" /><p>Taiwan (<code>TW</code>)</p></div>
    <div><CircleFlag countryCode="tz" /><p>Tanzania (<code>TZ</code>)</p></div>
    <div><CircleFlag countryCode="ua" /><p>Ukraine (<code>UA</code>)</p></div>
    <div><CircleFlag countryCode="ug" /><p>Uganda (<code>UG</code>)</p></div>
    <div><CircleFlag countryCode="united_nations" /><p>United Nations</p></div>
    <div><CircleFlag countryCode="xx" /><p>U.S. Minor Outlying Islands (<code>UM</code>)</p></div>
    <div><CircleFlag countryCode="us-hi"/><p>Hawaii</p></div>
    <div><CircleFlag countryCode="us" /><p>United States of America (<code>US</code>)</p></div>
    <div><CircleFlag countryCode="uy" /><p>Uruguay (<code>UY</code>)</p></div>
    <div><CircleFlag countryCode="uz" /><p>Uzbekistan (<code>UZ</code>)</p></div>
    <div><CircleFlag countryCode="va" /><p>Holy See (Vatican) (<code>VA</code>)</p></div>
    <div><CircleFlag countryCode="vc" /><p>Saint Vincent and the Grenadines (<code>VC</code>)</p></div>
    <div><CircleFlag countryCode="ve" /><p>Venezuela (<code>VE</code>)</p></div>
    <div><CircleFlag countryCode="vg" /><p>Virgin Islands (British) (<code>VG</code>)</p></div>
    <div><CircleFlag countryCode="vi" /><p>Virgin Islands (U.S.) (<code>VI</code>)</p></div>
    <div><CircleFlag countryCode="vn" /><p>Vietnam (<code>VN</code>)</p></div>
    <div><CircleFlag countryCode="vu" /><p>Vanuatu (<code>VU</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Wallis and Futuna (<code>WF</code>)</p></div>
    <div><CircleFlag countryCode="ws" /><p>Samoa (<code>WS</code>)</p></div>
    <div><CircleFlag countryCode="xk" /><p>Kosovo</p></div>
    <div><CircleFlag countryCode="xx" /><p>&lt;Placeholder&gt;</p></div>
    <div><CircleFlag countryCode="ye" /><p>Yemen (<code>YE</code>)</p></div>
    <div><CircleFlag countryCode="xx" /><p>Mayotte (<code>YT</code>)</p></div>
    <div><CircleFlag countryCode="yiddish" /><p>Yiddish</p></div>
    <div><CircleFlag countryCode="za" /><p>South Africa (<code>ZA</code>)</p></div>
    <div><CircleFlag countryCode="zm" /><p>Zambia (<code>ZM</code>)</p></div>
    <div><CircleFlag countryCode="zw" /><p>Zimbabwe (<code>ZW</code>)</p></div>
  </div>
</>

export default App
