import React from 'react'

import { CircleFlag } from 'react-circle-flags'
import 'react-circle-flags/dist/index.css'

const App = () => 
<>
<h1>Gallery</h1>
<div className="container">
  <div><CircleFlag country="ad" /><p>Andorra (<code>AD</code>)</p></div>
  <div><CircleFlag country="ae" /><p>United Arab Emirates (<code>AE</code>)</p></div>
  <div><CircleFlag country="af" /><p>Afghanistan (<code>AF</code>)</p></div>
  <div><CircleFlag country="ag" /><p>Antigua and Barbuda (<code>AG</code>)</p></div>
  <div><CircleFlag country="ai" /><p>Anguilla (<code>AI</code>)</p></div>
  <div><CircleFlag country="al" /><p>Albania (<code>AL</code>)</p></div>
  <div><CircleFlag country="am" /><p>Armenia (<code>AM</code>)</p></div>
  <div><CircleFlag country="ao" /><p>Angola (<code>AO</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Antarctica (<code>AQ</code>)</p></div>
  <div><CircleFlag country="ar" /><p>Argentina (<code>AR</code>)</p></div>
  <div><CircleFlag country="as" /><p>American Samoa (<code>AS</code>)</p></div>
  <div><CircleFlag country="at" /><p>Austria (<code>AT</code>)</p></div>
  <div><CircleFlag country="au" /><p>Australia (<code>AU</code>)</p></div>
  <div><CircleFlag country="aw" /><p>Aruba (<code>AW</code>)</p></div>
  <div><CircleFlag country="ax" /><p>Åland Islands (<code>AX</code>)</p></div>
  <div><CircleFlag country="az" /><p>Azerbaijan (<code>AZ</code>)</p></div>
  <div><CircleFlag country="ba" /><p>Bosnia and Herzegovina (<code>BA</code>)</p></div>
  <div><CircleFlag country="bb" /><p>Barbados (<code>BB</code>)</p></div>
  <div><CircleFlag country="bd" /><p>Bangladesh (<code>BD</code>)</p></div>
  <div><CircleFlag country="be" /><p>Belgium (<code>BE</code>)</p></div>
  <div><CircleFlag country="bf" /><p>Burkina Faso (<code>BF</code>)</p></div>
  <div><CircleFlag country="bg" /><p>Bulgaria (<code>BG</code>)</p></div>
  <div><CircleFlag country="bh" /><p>Bahrain (<code>BH</code>)</p></div>
  <div><CircleFlag country="bi" /><p>Burundi (<code>BI</code>)</p></div>
  <div><CircleFlag country="bj" /><p>Benin (<code>BJ</code>)</p></div>
  <div><CircleFlag country="bl" /><p>Saint Barthélemy (<code>BL</code>)</p></div>
  <div><CircleFlag country="bm" /><p>Bermuda (<code>BM</code>)</p></div>
  <div><CircleFlag country="bn" /><p>Brunei (<code>BN</code>)</p></div>
  <div><CircleFlag country="bo" /><p>Bolivia (<code>BO</code>)</p></div>
  <div><CircleFlag country="bq-bo"/><p>Bonaire (<code>BQ</code>)</p></div>
  <div><CircleFlag country="bq-sa"/><p>Saba (<code>BQ</code>)</p></div>
  <div><CircleFlag country="bq-se"/><p>Sint Eustatius (<code>BQ</code>)</p></div>
  <div><CircleFlag country="br" /><p>Brazil (<code>BR</code>)</p></div>
  <div><CircleFlag country="bs" /><p>Bahamas (<code>BS</code>)</p></div>
  <div><CircleFlag country="bt" /><p>Bhutan (<code>BT</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Bouvet Island (<code>BV</code>)</p></div>
  <div><CircleFlag country="bw" /><p>Botswana (<code>BW</code>)</p></div>
  <div><CircleFlag country="by" /><p>Belarus (<code>BY</code>)</p></div>
  <div><CircleFlag country="bz" /><p>Belize (<code>BZ</code>)</p></div>
  <div><CircleFlag country="ca-bc"/><p>British Columbia</p></div>
  <div><CircleFlag country="ca" /><p>Canada (<code>CA</code>)</p></div>
  <div><CircleFlag country="cc" /><p>Cocos (Keeling) Islands (<code>CC</code>)</p></div>
  <div><CircleFlag country="cd" /><p>Congo, Democratic Republic of the (<code>CD</code>)</p></div>
  <div><CircleFlag country="cf" /><p>Central African Republic (<code>CF</code>)</p></div>
  <div><CircleFlag country="cg" /><p>Congo (<code>CG</code>)</p></div>
  <div><CircleFlag country="ch" /><p>Switzerland (<code>CH</code>)</p></div>
  <div><CircleFlag country="ci" /><p>Ivory Coast (<code>CI</code>)</p></div>
  <div><CircleFlag country="ck" /><p>Cook Islands (<code>CK</code>)</p></div>
  <div><CircleFlag country="cl" /><p>Chile (<code>CL</code>)</p></div>
  <div><CircleFlag country="cm" /><p>Cameroon (<code>CM</code>)</p></div>
  <div><CircleFlag country="cn" /><p>China (<code>CN</code>)</p></div>
  <div><CircleFlag country="co" /><p>Colombia (<code>CO</code>)</p></div>
  <div><CircleFlag country="cr" /><p>Costa Rica (<code>CR</code>)</p></div>
  <div><CircleFlag country="cu" /><p>Cuba (<code>CU</code>)</p></div>
  <div><CircleFlag country="cv" /><p>Cabo Verde (<code>CV</code>)</p></div>
  <div><CircleFlag country="cw" /><p>Curaçao (<code>CW</code>)</p></div>
  <div><CircleFlag country="cx" /><p>Christmas Island (<code>CX</code>)</p></div>
  <div><CircleFlag country="cy" /><p>Cyprus (<code>CY</code>)</p></div>
  <div><CircleFlag country="cz" /><p>Czechia (<code>CZ</code>)</p></div>
  <div><CircleFlag country="de" /><p>Germany (<code>DE</code>)</p></div>
  <div><CircleFlag country="dj" /><p>Djibouti (<code>DJ</code>)</p></div>
  <div><CircleFlag country="dk" /><p>Denmark (<code>DK</code>)</p></div>
  <div><CircleFlag country="dm" /><p>Dominica (<code>DM</code>)</p></div>
  <div><CircleFlag country="do" /><p>Dominican Republic (<code>DO</code>)</p></div>
  <div><CircleFlag country="dz" /><p>Algeria (<code>DZ</code>)</p></div>
  <div><CircleFlag country="easter_island" /><p>Easter Island</p></div>
  <div><CircleFlag country="ec-w"/><p>Galápagos</p></div>
  <div><CircleFlag country="ec" /><p>Ecuador (<code>EC</code>)</p></div>
  <div><CircleFlag country="ee" /><p>Estonia (<code>EE</code>)</p></div>
  <div><CircleFlag country="eg" /><p>Egypt (<code>EG</code>)</p></div>
  <div><CircleFlag country="eh" /><p>Western Sahara (<code>EH</code>)</p></div>
  <div><CircleFlag country="er" /><p>Eritrea (<code>ER</code>)</p></div>
  <div><CircleFlag country="es-ce"/><p>Ceuta</p></div>
  <div><CircleFlag country="es-cn"/><p>Canary Islands</p></div>
  <div><CircleFlag country="es-ga"/><p>Galicia</p></div>
  <div><CircleFlag country="es-ib"/><p>Balearic Islands</p></div>
  <div><CircleFlag country="es-ml"/><p>Melilla</p></div>
  <div><CircleFlag country="es-pv"/><p>Basque Country</p></div>
  <div><CircleFlag country="es" /><p>Spain (<code>ES</code>)</p></div>
  <div><CircleFlag country="esperanto" /><p>Esperanto</p></div>
  <div><CircleFlag country="et" /><p>Ethiopia (<code>ET</code>)</p></div>
  <div><CircleFlag country="european_union" /><p>European Union</p></div>
  <div><CircleFlag country="fi" /><p>Finland (<code>FI</code>)</p></div>
  <div><CircleFlag country="fj" /><p>Fiji (<code>FJ</code>)</p></div>
  <div><CircleFlag country="fk" /><p>Falkland Islands (Malvinas) (<code>FK</code>)</p></div>
  <div><CircleFlag country="fm" /><p>Micronesia (<code>FM</code>)</p></div>
  <div><CircleFlag country="fo" /><p>Faroe Islands (<code>FO</code>)</p></div>
  <div><CircleFlag country="fr-h"/><p>Corsica</p></div>
  <div><CircleFlag country="fr" /><p>France (<code>FR</code>)</p></div>
  <div><CircleFlag country="ga" /><p>Gabon (<code>GA</code>)</p></div>
  <div><CircleFlag country="gb-eng"/><p>England</p></div>
  <div><CircleFlag country="gb-ork"/><p>Orkney</p></div>
  <div><CircleFlag country="gb-sct"/><p>Scotland</p></div>
  <div><CircleFlag country="gb-wls"/><p>Wales</p></div>
  <div><CircleFlag country="gb" /><p>United Kingdom (<code>GB</code>)</p></div>
  <div><CircleFlag country="gd" /><p>Grenada (<code>GD</code>)</p></div>
  <div><CircleFlag country="ge-ab"/><p>Georgia (<code>GE</code>)</p></div>
  <div><CircleFlag country="ge" /><p>French Guiana (<code>GF</code>)</p></div>
  <div><CircleFlag country="gg" /><p>Guernsey (<code>GG</code>)</p></div>
  <div><CircleFlag country="gh" /><p>Ghana (<code>GH</code>)</p></div>
  <div><CircleFlag country="gi" /><p>Gibraltar (<code>GI</code>)</p></div>
  <div><CircleFlag country="gl" /><p>Greenland (<code>GL</code>)</p></div>
  <div><CircleFlag country="gm" /><p>Gambia (<code>GM</code>)</p></div>
  <div><CircleFlag country="gn" /><p>Guinea (<code>GN</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Guadeloupe (<code>GP</code>)</p></div>
  <div><CircleFlag country="gq" /><p>Equatorial Guinea (<code>GQ</code>)</p></div>
  <div><CircleFlag country="gr" /><p>Greece (<code>GR</code>)</p></div>
  <div><CircleFlag country="xx" /><p>South Georgia and the South Sandwich Islands (<code>GS</code>)</p></div>
  <div><CircleFlag country="gt" /><p>Guatemala (<code>GT</code>)</p></div>
  <div><CircleFlag country="gu" /><p>Guam (<code>GU</code>)</p></div>
  <div><CircleFlag country="gw" /><p>Guinea-Bissau (<code>GW</code>)</p></div>
  <div><CircleFlag country="gy" /><p>Guyana (<code>GY</code>)</p></div>
  <div><CircleFlag country="hausa" /><p>Hausa</p></div>
  <div><CircleFlag country="hk" /><p>Hong Kong (<code>HK</code>)</p></div>
  <div><CircleFlag country="hmong" /><p>Hmong</p></div>
  <div><CircleFlag country="xx" /><p>Heard Island and McDonald Islands (<code>HM</code>)</p></div>
  <div><CircleFlag country="hn" /><p>Honduras (<code>HN</code>)</p></div>
  <div><CircleFlag country="hr" /><p>Croatia (<code>HR</code>)</p></div>
  <div><CircleFlag country="ht" /><p>Haiti (<code>HT</code>)</p></div>
  <div><CircleFlag country="hu" /><p>Hungary (<code>HU</code>)</p></div>
  <div><CircleFlag country="id" /><p>Indonesia (<code>ID</code>)</p></div>
  <div><CircleFlag country="ie" /><p>Ireland (<code>IE</code>)</p></div>
  <div><CircleFlag country="il" /><p>Israel (<code>IL</code>)</p></div>
  <div><CircleFlag country="im" /><p>Isle of Man (<code>IM</code>)</p></div>
  <div><CircleFlag country="in" /><p>India (<code>IN</code>)</p></div>
  <div><CircleFlag country="io" /><p>British Indian Ocean Territory (<code>IO</code>)</p></div>
  <div><CircleFlag country="iq" /><p>Iraq (<code>IQ</code>)</p></div>
  <div><CircleFlag country="ir" /><p>Iran (<code>IR</code>)</p></div>
  <div><CircleFlag country="is" /><p>Iceland (<code>IS</code>)</p></div>
  <div><CircleFlag country="it-82"/><p>Sicily</p></div>
  <div><CircleFlag country="it-88"/><p>Sardinia</p></div>
  <div><CircleFlag country="it" /><p>Italy (<code>IT</code>)</p></div>
  <div><CircleFlag country="je" /><p>Jersey (<code>JE</code>)</p></div>
  <div><CircleFlag country="jm" /><p>Jamaica (<code>JM</code>)</p></div>
  <div><CircleFlag country="jo" /><p>Jordan (<code>JO</code>)</p></div>
  <div><CircleFlag country="jp" /><p>Japan (<code>JP</code>)</p></div>
  <div><CircleFlag country="kannada" /><p>Kannada</p></div>
  <div><CircleFlag country="ke" /><p>Kenya (<code>KE</code>)</p></div>
  <div><CircleFlag country="kg" /><p>Kyrgyzstan (<code>KG</code>)</p></div>
  <div><CircleFlag country="kh" /><p>Cambodia (<code>KH</code>)</p></div>
  <div><CircleFlag country="ki" /><p>Kiribati (<code>KI</code>)</p></div>
  <div><CircleFlag country="km" /><p>Comoros (<code>KM</code>)</p></div>
  <div><CircleFlag country="kn" /><p>Saint Kitts and Nevis (<code>KN</code>)</p></div>
  <div><CircleFlag country="kp" /><p>North Korea (<code>KP</code>)</p></div>
  <div><CircleFlag country="kr" /><p>South Korea (<code>KR</code>)</p></div>
  <div><CircleFlag country="kurdistan" /><p>Kurdistan</p></div>
  <div><CircleFlag country="kw" /><p>Kuwait (<code>KW</code>)</p></div>
  <div><CircleFlag country="ky" /><p>Cayman Islands (<code>KY</code>)</p></div>
  <div><CircleFlag country="kz" /><p>Kazakhstan (<code>KZ</code>)</p></div>
  <div><CircleFlag country="la" /><p>Laos (<code>LA</code>)</p></div>
  <div><CircleFlag country="lb" /><p>Lebanon (<code>LB</code>)</p></div>
  <div><CircleFlag country="lc" /><p>Saint Lucia (<code>LC</code>)</p></div>
  <div><CircleFlag country="li" /><p>Liechtenstein (<code>LI</code>)</p></div>
  <div><CircleFlag country="lk" /><p>Sri Lanka (<code>LK</code>)</p></div>
  <div><CircleFlag country="lr" /><p>Liberia (<code>LR</code>)</p></div>
  <div><CircleFlag country="ls" /><p>Lesotho (<code>LS</code>)</p></div>
  <div><CircleFlag country="lt" /><p>Lithuania (<code>LT</code>)</p></div>
  <div><CircleFlag country="lu" /><p>Luxembourg (<code>LU</code>)</p></div>
  <div><CircleFlag country="lv" /><p>Latvia (<code>LV</code>)</p></div>
  <div><CircleFlag country="ly" /><p>Libya (<code>LY</code>)</p></div>
  <div><CircleFlag country="ma" /><p>Morocco (<code>MA</code>)</p></div>
  <div><CircleFlag country="malayali" /><p>Malayali</p></div>
  <div><CircleFlag country="maori" /><p>Maori</p></div>
  <div><CircleFlag country="mc" /><p>Monaco (<code>MC</code>)</p></div>
  <div><CircleFlag country="md" /><p>Moldova (<code>MD</code>)</p></div>
  <div><CircleFlag country="me" /><p>Montenegro (<code>ME</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Saint-Martin (<code>MF</code>)</p></div>
  <div><CircleFlag country="mg" /><p>Madagascar (<code>MG</code>)</p></div>
  <div><CircleFlag country="mh" /><p>Marshall Islands (<code>MH</code>)</p></div>
  <div><CircleFlag country="mk" /><p>North Macedonia (<code>MK</code>)</p></div>
  <div><CircleFlag country="ml" /><p>Mali (<code>ML</code>)</p></div>
  <div><CircleFlag country="mm" /><p>Myanmar (<code>MM</code>)</p></div>
  <div><CircleFlag country="mn" /><p>Mongolia (<code>MN</code>)</p></div>
  <div><CircleFlag country="mo" /><p>Macao (<code>MO</code>)</p></div>
  <div><CircleFlag country="mp" /><p>Northern Mariana Islands (<code>MP</code>)</p></div>
  <div><CircleFlag country="mq" /><p>Martinique (<code>MQ</code>)</p></div>
  <div><CircleFlag country="mr" /><p>Mauritania (<code>MR</code>)</p></div>
  <div><CircleFlag country="ms" /><p>Montserrat (<code>MS</code>)</p></div>
  <div><CircleFlag country="mt" /><p>Malta (<code>MT</code>)</p></div>
  <div><CircleFlag country="mu" /><p>Mauritius (<code>MU</code>)</p></div>
  <div><CircleFlag country="mv" /><p>Maldives (<code>MV</code>)</p></div>
  <div><CircleFlag country="mw" /><p>Malawi (<code>MW</code>)</p></div>
  <div><CircleFlag country="mx" /><p>Mexico (<code>MX</code>)</p></div>
  <div><CircleFlag country="my" /><p>Malaysia (<code>MY</code>)</p></div>
  <div><CircleFlag country="mz" /><p>Mozambique (<code>MZ</code>)</p></div>
  <div><CircleFlag country="na" /><p>Namibia (<code>NA</code>)</p></div>
  <div><CircleFlag country="xx" /><p>New Caledonia (<code>NC</code>)</p></div>
  <div><CircleFlag country="nato" /><p>NATO</p></div>
  <div><CircleFlag country="ne" /><p>Niger (<code>NE</code>)</p></div>
  <div><CircleFlag country="nf" /><p>Norfolk Island (<code>NF</code>)</p></div>
  <div><CircleFlag country="ng" /><p>Nigeria (<code>NG</code>)</p></div>
  <div><CircleFlag country="ni" /><p>Nicaragua (<code>NI</code>)</p></div>
  <div><CircleFlag country="nl" /><p>Netherlands (<code>NL</code>)</p></div>
  <div><CircleFlag country="no" /><p>Norway (<code>NO</code>)</p></div>
  <div><CircleFlag country="northern_cyprus" /><p>Northern Cyprus</p></div>
  <div><CircleFlag country="np" /><p>Nepal (<code>NP</code>)</p></div>
  <div><CircleFlag country="nr" /><p>Nauru (<code>NR</code>)</p></div>
  <div><CircleFlag country="nu" /><p>Niue (<code>NU</code>)</p></div>
  <div><CircleFlag country="nz" /><p>New Zealand (<code>NZ</code>)</p></div>
  <div><CircleFlag country="om" /><p>Oman (<code>OM</code>)</p></div>
  <div><CircleFlag country="pa" /><p>Panama (<code>PA</code>)</p></div>
  <div><CircleFlag country="pe" /><p>Peru (<code>PE</code>)</p></div>
  <div><CircleFlag country="pf" /><p>French Polynesia (<code>PF</code>)</p></div>
  <div><CircleFlag country="pg" /><p>Papua New Guinea (<code>PG</code>)</p></div>
  <div><CircleFlag country="ph" /><p>Philippines (<code>PH</code>)</p></div>
  <div><CircleFlag country="pk" /><p>Pakistan (<code>PK</code>)</p></div>
  <div><CircleFlag country="pl" /><p>Poland (<code>PL</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Saint Pierre and Miquelon (<code>PM</code>)</p></div>
  <div><CircleFlag country="pn" /><p>Pitcairn Islands (<code>PN</code>)</p></div>
  <div><CircleFlag country="pr" /><p>Puerto Rico (<code>PR</code>)</p></div>
  <div><CircleFlag country="ps" /><p>Palestine (<code>PS</code>)</p></div>
  <div><CircleFlag country="pt-20"/><p>Azores</p></div>
  <div><CircleFlag country="pt-30"/><p>Madeira</p></div>
  <div><CircleFlag country="pt" /><p>Portugal (<code>PT</code>)</p></div>
  <div><CircleFlag country="pw" /><p>Palau (<code>PW</code>)</p></div>
  <div><CircleFlag country="py" /><p>Paraguay (<code>PY</code>)</p></div>
  <div><CircleFlag country="qa" /><p>Qatar (<code>QA</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Réunion (<code>RE</code>)</p></div>
  <div><CircleFlag country="ro" /><p>Romania (<code>RO</code>)</p></div>
  <div><CircleFlag country="rs" /><p>Serbia (<code>RS</code>)</p></div>
  <div><CircleFlag country="ru" /><p>Russia (<code>RU</code>)</p></div>
  <div><CircleFlag country="rw" /><p>Rwanda (<code>RW</code>)</p></div>
  <div><CircleFlag country="sa" /><p>Saudi Arabia (<code>SA</code>)</p></div>
  <div><CircleFlag country="sb" /><p>Solomon Islands (<code>SB</code>)</p></div>
  <div><CircleFlag country="sc" /><p>Seychelles (<code>SC</code>)</p></div>
  <div><CircleFlag country="sd" /><p>Sudan (<code>SD</code>)</p></div>
  <div><CircleFlag country="se" /><p>Sweden (<code>SE</code>)</p></div>
  <div><CircleFlag country="sg" /><p>Singapore (<code>SG</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Saint Helena (<code>SH-HL</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Ascension Island (<code>SH-AC</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Tristan da Cunha (<code>SH-TA</code>)</p></div>
  <div><CircleFlag country="si" /><p>Slovenia (<code>SI</code>)</p></div>
  <div><CircleFlag country="sindh" /><p>Svalbard and Jan Mayen (<code>SJ</code>)</p></div>
  <div><CircleFlag country="sk" /><p>Slovakia (<code>SK</code>)</p></div>
  <div><CircleFlag country="sl" /><p>Sierra Leone (<code>SL</code>)</p></div>
  <div><CircleFlag country="sm" /><p>San Marino (<code>SM</code>)</p></div>
  <div><CircleFlag country="sn" /><p>Senegal (<code>SN</code>)</p></div>
  <div><CircleFlag country="so" /><p>Somalia (<code>SO</code>)</p></div>
  <div><CircleFlag country="somaliland" /><p>Somaliland</p></div>
  <div><CircleFlag country="south_ossetia" /><p>South Ossetia</p></div>
  <div><CircleFlag country="sr" /><p>Suriname (<code>SR</code>)</p></div>
  <div><CircleFlag country="ss" /><p>South Sudan (<code>SS</code>)</p></div>
  <div><CircleFlag country="st" /><p>São Tomé and Príncipe (<code>ST</code>)</p></div>
  <div><CircleFlag country="sv" /><p>El Salvador (<code>SV</code>)</p></div>
  <div><CircleFlag country="sx" /><p>Sint Maarten (<code>SX</code>)</p></div>
  <div><CircleFlag country="sy" /><p>Syria (<code>SY</code>)</p></div>
  <div><CircleFlag country="sz" /><p>Eswatini (<code>SZ</code>)</p></div>
  <div><CircleFlag country="tc" /><p>Turks and Caicos Islands (<code>TC</code>)</p></div>
  <div><CircleFlag country="td" /><p>Chad (<code>TD</code>)</p></div>
  <div><CircleFlag country="xx" /><p>French Southern Territories (<code>TF</code>)</p></div>
  <div><CircleFlag country="tg" /><p>Togo (<code>TG</code>)</p></div>
  <div><CircleFlag country="th" /><p>Thailand (<code>TH</code>)</p></div>
  <div><CircleFlag country="tibet" /><p>Tibet</p></div>
  <div><CircleFlag country="tj" /><p>Tajikistan (<code>TJ</code>)</p></div>
  <div><CircleFlag country="tk" /><p>Tokelau (<code>TK</code>)</p></div>
  <div><CircleFlag country="tl" /><p>Timor-Leste (<code>TL</code>)</p></div>
  <div><CircleFlag country="tm" /><p>Turkmenistan (<code>TM</code>)</p></div>
  <div><CircleFlag country="tn" /><p>Tunisia (<code>TN</code>)</p></div>
  <div><CircleFlag country="to" /><p>Tonga (<code>TO</code>)</p></div>
  <div><CircleFlag country="tr" /><p>Turkey (<code>TR</code>)</p></div>
  <div><CircleFlag country="transnistria" /><p>Transnistria</p></div>
  <div><CircleFlag country="tt" /><p>Trinidad and Tobago (<code>TT</code>)</p></div>
  <div><CircleFlag country="tv" /><p>Tuvalu (<code>TV</code>)</p></div>
  <div><CircleFlag country="tw" /><p>Taiwan (<code>TW</code>)</p></div>
  <div><CircleFlag country="tz" /><p>Tanzania (<code>TZ</code>)</p></div>
  <div><CircleFlag country="ua" /><p>Ukraine (<code>UA</code>)</p></div>
  <div><CircleFlag country="ug" /><p>Uganda (<code>UG</code>)</p></div>
  <div><CircleFlag country="united_nations" /><p>United Nations</p></div>
  <div><CircleFlag country="xx" /><p>U.S. Minor Outlying Islands (<code>UM</code>)</p></div>
  <div><CircleFlag country="us-hi"/><p>Hawaii</p></div>
  <div><CircleFlag country="us" /><p>United States of America (<code>US</code>)</p></div>
  <div><CircleFlag country="uy" /><p>Uruguay (<code>UY</code>)</p></div>
  <div><CircleFlag country="uz" /><p>Uzbekistan (<code>UZ</code>)</p></div>
  <div><CircleFlag country="va" /><p>Holy See (Vatican) (<code>VA</code>)</p></div>
  <div><CircleFlag country="vc" /><p>Saint Vincent and the Grenadines (<code>VC</code>)</p></div>
  <div><CircleFlag country="ve" /><p>Venezuela (<code>VE</code>)</p></div>
  <div><CircleFlag country="vg" /><p>Virgin Islands (British) (<code>VG</code>)</p></div>
  <div><CircleFlag country="vi" /><p>Virgin Islands (U.S.) (<code>VI</code>)</p></div>
  <div><CircleFlag country="vn" /><p>Vietnam (<code>VN</code>)</p></div>
  <div><CircleFlag country="vu" /><p>Vanuatu (<code>VU</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Wallis and Futuna (<code>WF</code>)</p></div>
  <div><CircleFlag country="ws" /><p>Samoa (<code>WS</code>)</p></div>
  <div><CircleFlag country="xk" /><p>Kosovo</p></div>
  <div><CircleFlag country="xx" /><p>&lt;Placeholder&gt;</p></div>
  <div><CircleFlag country="ye" /><p>Yemen (<code>YE</code>)</p></div>
  <div><CircleFlag country="xx" /><p>Mayotte (<code>YT</code>)</p></div>
  <div><CircleFlag country="yiddish" /><p>Yiddish</p></div>
  <div><CircleFlag country="za" /><p>South Africa (<code>ZA</code>)</p></div>
  <div><CircleFlag country="zm" /><p>Zambia (<code>ZM</code>)</p></div>
  <div><CircleFlag country="zw" /><p>Zimbabwe (<code>ZW</code>)</p></div>
</div>
</>

export default App
